# Set the name of the Spring Boot application
spring:
  application:
    name: VLSA-ADMIN

  # Set the configuration for connecting to the PostgreSQL database
  datasource:
    url: jdbc:postgresql://10.1.177.120:5432/vsla_admin
    username: postgres
    password: 1313

  # Set the configuration for Hibernate, the ORM framework used by Spring Data JPA
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update  # Set the strategy for Hibernate to create/update the database schema. Hibernate ddl auto (create, create-drop, validate, update)
    show-sql: true

  # Set the configuration for handling multipart file uploads
  servlet:
    multipart:
      max-file-size: 10MB # Maximum size of each file in a multipart request
      max-request-size: 10MB # Maximum size of the entire multipart request

# Set the port number for the web server.
server:
  port: 8112

# Set the conditional property for seeding the database
# NOTE: Set it to true only if you are starting this app for the first time.
database:
  seed: false

# Secret key for jwt
JWT_SECRET_KEY:
  AB(G+KbPeShVkYp3s6v9y$B&E)H@McQf

# vsla base url
VSLA_APP:
  BASE_URL: http://10.1.177.121:8111/api/v1/
